# Generated by Django 5.0.3 on 2024-03-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='review_history',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='favourite_movies',
            field=models.ManyToManyField(
                related_name='favourite_movies', to='review.movie'
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
