# Generated by Django 5.0.3 on 2024-03-28 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_reviewer_review_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title', 'release_year')},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='movie',
            name='reviewers',
            field=models.ManyToManyField(
                related_name='reviewed_movies',
                through='review.Review',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviews',
            field=models.ManyToManyField(
                related_name='reviews_written', to='review.review'
            ),
        ),
    ]
