# Generated by Django 5.0.3 on 2024-03-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_genre_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='reviews',
        ),
    ]
