# Generated by Django 5.0.3 on 2024-03-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_remove_reviewer_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_reviews",
                to="review.movie",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
